from langchain_tavily import TavilySearch, TavilyExtract
from dotenv import load_dotenv
from pprint import pprint

load_dotenv()

t1 = TavilySearch(
    max_results=5,
    topic="general",
    # include_answer=False,
    # include_raw_content=False,
    # include_images=False,
    # include_image_descriptions=False,
    search_depth="advanced",
    # time_range="day",
    # include_domains=None,
    # exclude_domains=None
)


t2 = TavilyExtract(
    extract_depth="advanced",
    include_images=False,
)

# # This is usually generated by a model, but we'll create a tool call directly for demo purposes.
# gt1 = {
#     "args": {"query": "pizza country of origin"},
#     "id": "1",
#     "name": "tavily",
#     "type": "tool_call",
# }
# m1 = t1.invoke(gt1)
# pprint(m1.content)

# This is usually generated by a model, but we'll create a tool call directly for demo purposes.
gt2 = {
    "args": {"urls": ["https://www.infernobyfire.com/pizza-history-101"]},
    "id": "1",
    "name": "tavily",
    "type": "tool_call",
}
m2 = t2.invoke(gt2)
d2 = m2.dict()
pprint(d2)
